### ISSUE TITLE
Support for multiple stops

### ISSUE THREAD

**Issue by romanofski** [romanofski/gtfsbrisbane#1]
A typical scenario is to monitor departing services from multiple stops, because they could be both departing from the same complex. For example, trains could depart from multiple stops since stop a is used by express and stop b is used by normal trains.

**Comment by frasertweedale** [comment]
:+1: I have a similar scenario: two bus stops near my house, serviced by totally different inbound routes.  Need to know which to go to for next service :)

Note that walk time is different to each stop, so need to be able to specify `(Stop, Walktime)` pairs.

**Comment by romanofski** [comment]
Actually that's an interesting scenario. For me it's mostly one stop (walktime is fixed) and the travel time is so similar, that I can take whatever is next. But I guess that is more the exception than the rule.

I guess for you it's also travel time which is different? Same departure time?

**Comment by frasertweedale** [comment]
Yeah, yours is a special case, really.  Anyhow I'm working on this already.

Because you need to specify one or more `(Stop, Walktime)` pairs on command line, I propose changing to positional args of format `STOP-ID [ "+" MINUTES ]`, e.g.: `002233+5` (five minute walktime), or `002254` (default to zero walktime).  You just list off one or more of those as positional args.

Feedback?

**Comment by romanofski** [comment]
On December 8, 2016 10:00:20 PM GMT+10:00, Fraser Tweedale <notifications@github.com> wrote:
>Yeah, yours is a special case, really.  Anyhow I'm working on this
>already.

:-O

>Because you need to specify one or more `(Stop, Walktime)` pairs on
>command line, I propose changing to positional args of format `STOP-ID
>[ ":" MINUTES ]`, e.g.: `002233+5` (five minute walktime), or `002233`
>(default to zero walktime).

Sounds great!


-- 
Sent from a mobile device.
