### ISSUE TITLE
Add option to prefix the stop_name

### ISSUE THREAD

**Issue by djansen-redhat** [romanofski/gtfsbrisbane#16]
Something (like a -n option) to show the stop_name attribute, so I get output like 
Roma Street station, platform 8, City: RPSP Springfield Central 2min (14:15:00)

**Comment by romanofski** [comment]
There is no way around to introduce a config file at some point (e.g. just to nominate that you want to use a GTFS feed and static data from somewhere else if you're not in Brisbane).

So having a config file, might as well allow the user to configure the output (e.g. a template string)? There are a few cases I could see where adding a stop is very useful. If I use it as a status bar widget where (character space) is crucial, I might want to not show it or use a short name.

**Comment by romanofski** [comment]
This is being shipped with 0.7. Can be configured with the template using the `$stopName$` template field.
